version: "3.3"

services:
  gravar-vendedor:
    image: "gravar-vendedor:${CODE_SC_HG}"
    ports:
      - 8083:8083
    environment:
      - spring_datasource_url=jdbc:postgresql://192.168.0.15/gnus
      - s3_host=http://192.168.0.15:9444/s3
      - kafka_bootstrap-servers=192.168.0.15:9092
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

