version: "3.3"

services:
  leitor-ftp:
    image: "leitor-ftp:${CODE_SC_HG}"
    ports:
      - 8081:8080
    environment:
      - spring_datasource_url=jdbc:postgresql://192.168.0.15/gnus
      - s3_host=http://192.168.0.15:9444/s3
      - ftp_server=192.168.0.15
      - kafka_bootstrap-servers=192.168.0.15:9092
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

