kafka:
  bootstrap-servers: 127.0.0.1:9092
  consumergroup: garvarvendedor-group
  topicgravardados: topic-gravar-dados-arquivo-s1
  producer:
    max:
      request:
        size: 231072000
    batch-size: 60000000
    buffer-memory: 60000000
  client-id: garvarvendedor-producer
  consumer:
    group-id: garvarvendedor-group
    auto-offset-reset: earliest
    enable-auto-commit: false
